spring.application.name=NetPulse

#Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password= ${DB_PASSWORD}

# Hibernate auto create table active
spring.jpa.hibernate.ddl-auto=update
# show sql command active
spring.jpa.show-sql=true

#Swagger Configuration
# Cambia l'indirizzo dell'interfaccia grafica di Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# Cambia l'indirizzo dove viene generato il JSON dei dati OpenAPI
springdoc.api-docs.path=/api-docs

